name: ORT Analysis Workflow
on:
  workflow_dispatch:
    inputs:
      scan_id:
        description: 'Scan ID'
        required: true
      scan_type:
        description: 'Type of scan to perform'
        required: false
        default: 'standard'
      policy:
        description: 'Policy to apply'
        required: false
        default: 'strict'
      project_id:
        description: 'Project ID'
        required: false
        default: '6'
      target_repository_url:
        description: 'Target repository URL'
        required: true
        default: 'https://github.com/oss-review-toolkit/ort-ci-github-action'
      target_branch:
        description: 'Target branch'
        required: false
        default: 'develop'
      package_managers:
        description: 'Package managers to use'
        required: false
        default: 'npm,maven,gradle,pip'
      fail_on:
        description: 'What to fail on'
        required: false
        default: 'violations'
      run_stages:
        description: 'Stages to run'
        required: false
        default: 'analyzer,scanner,evaluator,reporter'
      webhook_url:
        description: 'Webhook URL for callbacks'
        required: true
        default: 'http://localhost:3000/api/scans/ort-callback'
      custom_policy_rules:
        description: 'Custom Policy Rules YAML'
        required: false

jobs:
  ort-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.target_repository_url }}
          ref: ${{ github.event.inputs.target_branch }}
          
      - name: Setup custom evaluator rules
        if: ${{ github.event.inputs.custom_policy_rules != '' }}
        run: |
          echo '${{ github.event.inputs.custom_policy_rules }}' > custom-rules.yml
          mkdir -p .ort/config
          mv custom-rules.yml .ort/config/
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Run ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          vcs-url: 'https://github.com/oss-review-toolkit/ort-ci-github-action'
          run: >-
              cache-dependencies,
              labels,
              analyzer,
              scanner,
              advisor,
              evaluator,
              reporter,
              upload-results
          ort-cli-args: '-P ort.scanner.skipExcluded=true'
        env:
          ORT_CONFIG_DIR: ${{ github.workspace }}/.ort/config
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ort-results
          path: |
            .ort/
            *.json
            *.html
            *.xlsx
            
      - name: Send webhook notification
        if: always()
        run: |
          curl -X POST "${{ github.event.inputs.webhook_url }}"             -H "Content-Type: application/json"             -d '{
              "scan_id": "${{ github.event.inputs.scan_id }}",
              "status": "${{ job.status }}",
              "run_id": "${{ github.run_id }}",
              "repository": "${{ github.repository }}",
              "conclusion": "${{ job.status }}"
            }'
