name: ORT License Compliance Scan
on:  
  workflow_dispatch:

jobs:
  ort-scan:
    runs-on: ubuntu-latest
    name: ORT License Compliance Check
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Setup ORT configuration files
      run: |
        # Create ORT config directory
        mkdir -p .ort/config

        # Copy evaluator rules to ORT config directory
        cp evaluator.rules.kts .ort/config/
        cp license-classifications.yml .ort/config/

        echo "ORT configuration files setup complete"
    - name: Clean ORT output directory
      run: rm -rf /home/ort/work/ort-analysis-repo/ort-analysis-repo && mkdir -p /home/ort/work/ort-analysis-repo/ort-analysis-repo
    - name: Run ORT
      uses: oss-review-toolkit/ort-ci-github-action@v1
      with:
        vcs-url: 'https://github.com/WebGoat/WebGoat'
        run: >-
            cache-dependencies,
            labels,
            analyzer,
            scanner,
            advisor,
            evaluator,
            reporter,
            upload-results
        ort-cli-args: '-P ort.scanner.skipExcluded=true -P ort.evaluator.rulesFile=./.ort/config/evaluator.rules.kts'
        ort-cli-scan-args: '--package-types=PROJECT'
      env:
        ORT_CONFIG_DIR: ${{ github.workspace }}/.ort/config
