name: ORT Analysis Workflow
on:
  workflow_dispatch:
jobs:
  ort-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: https://github.com/oss-review-toolkit/ort-ci-github-action
   
              
      - name: Run ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          vcs-url: 'https://github.com/oss-review-toolkit/ort-ci-github-action'
          run: >-
              cache-dependencies,
              labels,
              analyzer,
              scanner,
              advisor,
              evaluator,
              reporter,
              upload-results
          ort-cli-args: '-P ort.scanner.skipExcluded=true'
          ort-cli-scan-args: '--package-types=PROJECT'
        env:
          ORT_CONFIG_DIR: ${{ github.workspace }}/.ort/config
          